apiVersion: v1
kind: Service
metadata:
  name: hwk-server
  labels:
    app: hwk-server
    service: hwk-server
spec:
  type: ClusterIP
  selector:
    app: hwk-server
  ports:
    - name: http
      port: 8080
    - name: grpc
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwk-server-v1
  labels:
    app: hwk-server
    version: v1
spec:
  selector:
    matchLabels:
      app: hwk-server
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: hwk-server
        version: v1
    spec:
      containers:
      - name: hwk-server
        image: registry:5000/hwk-server:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: grpc
