apiVersion: v1
kind: Service
metadata:
  name: hwk-client
  labels:
    app: hwk-client
    service: hwk-client
spec:
  type: LoadBalancer
  selector:
    app: hwk-client
  ports:
    - name: http
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwk-client-v1
  labels:
    app: hwk-client
    version: v1
spec:
  selector:
    matchLabels:
      app: hwk-client
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: hwk-client
        version: v1
    spec:
      containers:
      - name: hwk-client
        image: registry:5000/hwk-client:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http

